language: cpp
dist: trusty
os:
    - linux
complier:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-date-time-dev
script: cd src && make && make test
