language: cpp
dist: trusty
os:
    - linux
complier:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake libboost-date-time-dev libgtest-dev
script: mkdir -p gtest && cd gtest && cmake /usr/src/gtest && make && cd ../src && make && make test
